environment:

  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python35"

init:
- cmd: pip install nose numpy
- cmd: pip install -c Quantopian zipline
build_script:
- cmd: pip install .
test_script:
- cmd: nosetests
